EmileCalixte/LeQuiz.io

.github/pull_request_template.md
CONTRIBUTING.md

Created CONTRIBUTING.md and pull request template

Contributing

---

.gitignore
backend/package-lock.json
backend/package.json
backend/server.js

Initialize express server + nodemon package for hot reloading

Initialize Express Server

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/App.js
frontend/src/components/pages/CreateRoom.js
frontend/src/components/pages/Home.js
frontend/src/components/pages/JoinRoom.js
frontend/src/index.js

Created base router architecture with base components architecture.

Created base router with react-router

---

docker-compose.yml

| Fixed issues  | 
A simple workaround in docker-compose.yml to run the React App through Docker

Fix frontend process exit with docker-compose up

---

backend/scripts/start.sh
docker-compose.yml
frontend/scripts/start.sh

Those two simple scripts run "npm update" before starting the project
in order to install node dependencies if needed.

Created start script in frontend and backend

---

backend/scripts/start.sh
docker-compose.yml
frontend/scripts/start.sh

| Fixed issues  | 
Also added verbose option to `npm update` in backend and frontend start scripts.

Updated node version in backend & frontend images

---

backend/migrations/20201009160821-create-question.js
backend/models/dbModels/question.js

| New feature?  |No
| Fixed issues  | -
To handle difficulty of questions later

Added Difficulty Field To Question Model

---

backend/migrations/20201008143133-create-user.js
backend/migrations/20201008164307-create-category.js
backend/migrations/20201008165914-create-custom-quiz.js
backend/migrations/20201008172452-create-category-custom-quiz.js
backend/migrations/20201009160820-create-user-review.js
backend/migrations/20201009160821-create-question.js
backend/migrations/20201009175935-create-question-position.js
backend/migrations/20201009193257-create-subscription.js
backend/migrations/20201010112122-create-category-question.js
backend/models/dbModels/category.js
backend/models/dbModels/categorycustomquiz.js
backend/models/dbModels/categoryquestion.js
backend/models/dbModels/customquiz.js
backend/models/dbModels/question.js
backend/models/dbModels/questionposition.js
backend/models/dbModels/subscription.js
backend/models/dbModels/user.js
backend/models/dbModels/userreview.js
backend/package-lock.json
backend/package.json

| New feature?  No
Id is now UUID type instead of integer

ID To UUID

---

backend/scripts/start.sh
frontend/scripts/start.sh

Switch NPM Update To NPM Install

---

backend/routes/mainRouter.js
backend/routes/subRouters/adminRouter.js
backend/routes/subRouters/adminSubRouters/adminCategoriesRouter.js
backend/routes/subRouters/adminSubRouters/adminModeRouter.js
backend/routes/subRouters/adminSubRouters/adminQuestionTypesRouter.js
backend/routes/subRouters/adminSubRouters/adminQuestionsRouter.js
backend/routes/subRouters/adminSubRouters/adminRoomRouter.js
backend/routes/subRouters/adminSubRouters/adminUsersRouter.js
backend/routes/subRouters/authRouter.js
backend/routes/subRouters/gameRouter.js
backend/routes/subRouters/usersRouter.js
backend/server.js

Initialize Express Routing Implementation

---

backend/server.js

Removal of Double Connexion Sequelize

---

backend/server.js

Fix Imports Sequelize

---

frontend/src/util/Util.js

Remove useless line in Util.js

---

sql/import.sql

Add Refresh Token Table to DB

---

backend/models/dbModels/customquiz.js
backend/models/dbModels/question.js
backend/models/dbModels/user.js
backend/models/dbModels/userreview.js
backend/server.js

Create Model Class Const

---

backend/controllers/GameController.js

Create Game Controller

---

sql/import.sql

Changed fake user passwords to their hash

---

backend/controllers/GameController.js
backend/routes/subRouters/gameRouter.js
backend/server.js

generate code room

---

sql/import.sql

| Fixed issues  | 
This will allow us to store guests refresh tokens in this table, and to run a periodic task to remove expired refresh tokens from the table.

Added expirationDate column and userId nullable in refresh token table

---

frontend/src/util/Util.js

| Fixed issues  | Fixes #33 
API URL is now dynamic, depending on frontend URL (localhost or local network IP address for example)

Changed API URL in frontend to run app on local network

---

docker-compose.yml

Add Restart Policy To Backend Container

---

frontend/src/components/misc/NextButton.js
frontend/src/components/pages/CreateGame/views/ChooseCategories.js
frontend/src/css/style.css

Use id of category instead of id object which previously resulted in bugs.

Fix Choose Cat

---

backend/controllers/GameController.js
backend/models/gameModes/Ascension.js
backend/models/gameModes/Blitz.js
backend/models/gameModes/Serie.js
backend/models/gameModes/Survivant.js
backend/routes/subRouters/gameRouter.js
frontend/src/components/misc/NextButton.js
frontend/src/components/pages/CreateGame/CreateGame.js
frontend/src/components/pages/CreateGame/components/GameMode.js
frontend/src/components/pages/CreateGame/components/QuestionType.js
frontend/src/components/pages/CreateGame/components/QuestionTypes.js
frontend/src/components/pages/CreateGame/components/WinCriterion.js
frontend/src/components/pages/CreateGame/views/ChooseCategories.js
frontend/src/components/pages/CreateGame/views/ChooseGameMode.js
frontend/src/components/pages/CreateGame/views/ChooseOptions.js
frontend/src/components/pages/CreateGame/views/Room.js
frontend/src/css/style.css
frontend/src/util/GameUtil.js

Initialize Frontend Game Options

---

backend/controllers/UserController.js

generate guest name

---

CODE_OF_CONDUCT.md

Add Code of conduct

---

backend/manager/RoomManager.js
frontend/src/components/misc/BackArrow.js
frontend/src/components/pages/CreateGame/CreateGame.js
frontend/src/components/pages/CreateGame/views/ChooseCategories.js
frontend/src/components/pages/CreateGame/views/ChooseGameMode.js
frontend/src/components/pages/CreateGame/views/ChooseOptions.js
frontend/src/components/pages/Room/Room.js
frontend/src/components/pages/Room/components/Lobby/CategoriesBox.js
frontend/src/components/pages/Room/components/Lobby/GameModeBox.js
frontend/src/components/pages/Room/components/Lobby/OptionsBox.js
frontend/src/components/pages/Room/views/Lobby.js
frontend/src/manager/ClientSocket.js

Gives the possibility to users to navigate back using UI componant instead of browser element. It's particulary relevant in the flow of creating a game from scratch or editing options from a room.

Initialize Back Arrow Component

---

backend/controllers/UserController.js
backend/manager/RoomManager.js
backend/routes/mainRouter.js
backend/routes/subRouters/usersRouter.js
backend/util/GameUtil.js
frontend/src/components/pages/Room/Room.js

| Fixed issues  | Fixes
Generates a unique guest Id for guest users.

Generate GuestId For Non Registered Users

---

frontend/src/components/pages/Room/Room.js
frontend/src/components/pages/Room/components/Lobby/LeaveButton.js
frontend/src/components/pages/Room/components/Shared/LeaveRoomCross.js
frontend/src/components/pages/Room/views/Answer.js
frontend/src/components/pages/Room/views/Lobby.js
frontend/src/components/pages/Room/views/Question.js

| New feature?  | Ye
Gives Players the ability to leave a room with UI components

Leave room

---

backend/routes/subRouters/usersRouter.js

| New feature?  |No
Fix the generation of guest id

Fix Users Route

---

frontend/src/components/pages/CreateGame/components/GameMode.js
frontend/src/components/pages/CreateGame/views/ChooseGameMode.js
frontend/src/css/style.css

Change Design Of Game Mode Due To Better Understanding Of Flexbox

Change Design Of Game Mode Due To Better Understanding Of Flexbox
